don't mind me :))

diff --git a/system/bin/systemize b/system/bin/systemize
--- a/system/bin/systemize
+++ b/system/bin/systemize
@@ -28,64 +28,64 @@ set -x 2>$VERLOG
 
 #=========================== Determine if A/B OTA device
 if [ -d /system_root ]; then
-  isABDevice=true
-  SYSTEM=/system_root/system
-  SYSTEM2=/system
+	isABDevice=true
+	SYSTEM=/system_root/system
+	SYSTEM2=/system
 else
-  isABDevice=false
-  SYSTEM=/system
-  SYSTEM2=/system
+	isABDevice=false
+	SYSTEM=/system
+	SYSTEM2=/system
 fi
 
 #=========================== Set Busybox (Used by Magisk) up
 # > Do not touch!
 set_busybox() {
-  if [ -x "$1" ]; then
-    for i in $(${1} --list); do
-      if [ "$i" != 'echo' ]; then
-        alias "$i"="${1} $i" 2>>$LOG >>$LOG
-      fi
-    done
-    _busybox=true
-    _bb=$1
-  fi
+	if [ -x "$1" ]; then
+		for i in $(${1} --list); do
+			if [ "$i" != 'echo' ]; then
+				alias "$i"="${1} $i" 2>>$LOG >>$LOG
+			fi
+		done
+		_busybox=true
+		_bb=$1
+	fi
 }
 _busybox=false
 if [ -d /sbin/.core/busybox ]; then
-  PATH=$PATH:/sbin/.core/busybox
-  _bb=/sbin/.core/busybox/busybox
-  _busybox=true
+	PATH=$PATH:/sbin/.core/busybox
+	_bb=/sbin/.core/busybox/busybox
+	_busybox=true
 elif [ ! -x $SYSTEM/xbin/busybox ]; then
-  set_busybox /data/magisk/busybox
-  set_busybox /data/adb/magisk/busybox
+	set_busybox /data/magisk/busybox
+	set_busybox /data/adb/magisk/busybox
 else
-  alias busybox=""
+	alias busybox=""
 fi
 if [ -x $SYSTEM/xbin/busybox ]; then
-  _bb=$SYSTEM/xbin/busybox
+	_bb=$SYSTEM/xbin/busybox
 elif [ -x $SYSTEM/bin/busybox ]; then
-  _bb=$SYSTEM/bin/busybox
+	_bb=$SYSTEM/bin/busybox
 elif [ $_busybox ]; then
-  true
+	true
 else
-  echo "! Busybox not detected.."
-  echo "Please install one (@osm0sis' busybox recommended)"
-  false
+	echo "! Busybox not detected.."
+	echo "Please install one (@osm0sis' busybox recommended)"
+	false
 fi
 [ $? -ne 0 ] && exit $?
 _bbname=$(busybox | head -n1)
 _bbname=${_bbname%'('*}
 BBok=true
 if [ "$_bbname" == "" ]; then
-  _bbname="BusyBox not found!"
-  BBok=false
+	_bbname="BusyBox not found!"
+	BBok=false
 fi
 
 #=========================== Default Functions
 
 # set_file_prop <property> <value> <prop.file>
 set_file_prop() {
-  sed -i "s/${1}=.*/${1}=${2}/g" $3
+	sed -i "s/${1}=.*/${1}=${2}/g" $3
 }
 
 # https://github.com/fearside/ProgressBar
@@ -102,40 +102,39 @@ ProgressBar() {
 # 1.2.1 Output example:
 # 1.2.1.1 Progress : [########################################] 100%
 printf "\rProgress : [${_done// /=}${_left// / }] ${_progress}%%"
-
 }
 
 # "cmd & spinner [message]"
 spinner() {
-  PID=$!
-  h=0; anim='-\|/'; 
-  while [ -d /proc/$PID ]; do
-	h=$(((h+1)%4))
-	sleep 0.02
-	printf "\r$@ [${anim:$h:1}]"
-  done
+	PID=$!
+	h=0; anim='-\|/'; 
+	while [ -d /proc/$PID ]; do
+		h=$(((h+1)%4))
+		sleep 0.02
+		printf "\r$@ [${anim:$h:1}]"
+	done
 }
 
 # Log files will be uploaded to termbin.com
 upload_logs() {
-  $BBok && {
-    echo -n "Testing internet connection "
-    ping -q -c 1 -W 1 google.com >/dev/null 2>/dev/null && echo "- OK" || { echo "Error"; exit 1; }
-	verUp=none; oldverUp=none; logUp=none; oldlogUp=none;
-	echo "Uploading logs"
-	[ -s $VERLOG ] && verUp=$(cat $VERLOG | nc termbin.com 9999)
-    [ -s $oldVERLOG ] && oldverUp=$(cat $oldVERLOG | nc termbin.com 9999)
-    [ -s $LOG ] && logUp=$(cat $LOG | nc termbin.com 9999)
-    [ -s $oldLOG ] && oldlogUp=$(cat $oldLOG | nc termbin.com 9999)
-	echo -n "Link: "
-	echo "$MODEL ($DEVICE) API $API\n$ROM\n$ID\n
-	O_Verbose: $oldverUp
-	Verbose:   $verUp
+	$BBok && {
+		echo -n "Testing internet connection "
+		ping -q -c 1 -W 1 google.com >/dev/null 2>/dev/null && echo "- OK" || { echo "Error"; exit 1; }
+		verUp=none; oldverUp=none; logUp=none; oldlogUp=none;
+		echo "Uploading logs"
+		[ -s $VERLOG ] && verUp=$(cat $VERLOG | nc termbin.com 9999)
+		[ -s $oldVERLOG ] && oldverUp=$(cat $oldVERLOG | nc termbin.com 9999)
+		[ -s $LOG ] && logUp=$(cat $LOG | nc termbin.com 9999)
+		[ -s $oldLOG ] && oldlogUp=$(cat $oldLOG | nc termbin.com 9999)
+		echo -n "Link: "
+		echo "$MODEL ($DEVICE) API $API\n$ROM\n$ID\n
+		O_Verbose: $oldverUp
+		Verbose:   $verUp
 	
-	O_Log: $oldlogUp
-	Log:   $logUp" | nc termbin.com 9999
-  } || echo "Busybox not found!"
-  exit
+		O_Log: $oldlogUp
+		Log:   $logUp" | nc termbin.com 9999
+	} || echo "Busybox not found!"
+	exit
 }
 
 #=========================== Default Variables
@@ -145,18 +144,18 @@ upload_logs() {
 # Magisk Mod Directory
 MOUNTPATH=/magisk
 if [ ! -d $MOUNTPATH ]; then
-  if [ -d /sbin/.core/img ]; then
-    MOUNTPATH=/sbin/.core/img
-  fi
+	if [ -d /sbin/.core/img ]; then
+		MOUNTPATH=/sbin/.core/img
+	fi
 fi
 MODDIR="$MOUNTPATH/$ID"
 if [ ! -d $MODDIR ]; then
-  if [ -d /sbin/.core/img/$ID ]; then
-    MODDIR=/sbin/.core/img/$ID
-  else
-    echo "Module not detected!"
-    exit 1
-  fi
+	if [ -d /sbin/.core/img/$ID ]; then
+		MODDIR=/sbin/.core/img/$ID
+	else
+		echo "Module not detected!"
+		exit 1
+	fi
 fi
 
 # Import util_functions.sh
@@ -200,14 +199,14 @@ div="${Bl}$(printf '%*s' "$(echo $MODTITLE $VER $REL | tr " " '_' | wc -c)" '' |
 
 # Heading
 mod_head() {
-  clear
-  echo "$div"
-  echo "${W}$MODTITLE $VER${N}${Bl}($REL)${N}"
-  echo "by ${W}$AUTHOR${N}"
-  echo "$div"
-  echo "${W}$_bbname${N}"
-  echo "${Bl}$_bb${N}"
-  echo "$div"
+	clear
+	echo "$div"
+	echo "${W}$MODTITLE $VER${N}${Bl}($REL)${N}"
+	echo "by ${W}$AUTHOR${N}"
+	echo "$div"
+	echo "${W}$_bbname${N}"
+	echo "${Bl}$_bb${N}"
+	echo "$div"
 }
 
 #=========================== Main
