v12

diff --git a/system/bin/systemize b/system/bin/systemize
--- a/system/bin/systemize
+++ b/system/bin/systemize
@@ -9,18 +9,21 @@ ID="terminal_systemizer"
 
 #=========================== Check root
 _name=$0; _name=${_name##*/}
-echo "test root" > /data/local/tmp/temp 2>/dev/null >/dev/null
-[ $? -ne 0 ] && echo "$_name needs to be in a root shell!" && echo "type 'su' then '$_name'" && exit 1
+id | grep -q root
+[ $? -ne 0 ] && { echo "$ID needs to be in a root shell!"; echo "type 'su' then '$_name'"; exit 1; }
 
 #=========================== Set Log Files
 mount -o remount,rw /cache 2>/dev/null
 mount -o rw,remount /cache 2>/dev/null
 # > Logs should go in this file
 LOG=/cache/${ID}.log
+oldLOG=/cache/${ID}-old.log
 # > Verbose output goes here
 VERLOG=/cache/${ID}-verbose.log
+oldVERLOG=/cache/${ID}-verbose-old.log
 
 #=========================== Start Logging verbosely
+mv -f $VERLOG $oldVERLOG 2>/dev/null; mv -f $LOG $oldLOG 2>/dev/null
 set -x 2>$VERLOG
 
 #=========================== Determine if A/B OTA device
@@ -59,13 +62,9 @@ if [ ! -x $SYSTEM/xbin/busybox ]; then
   fi
 fi
 if [ -x $SYSTEM/xbin/busybox ]; then
-  true
   _bb=$SYSTEM/xbin/busybox
 elif [ -x $SYSTEM/bin/busybox ]; then
-  true
   _bb=$SYSTEM/bin/busybox
-elif [ -x /data/data/com.topjohnwu.magisk/busybox/busybox ]; then
-  export PATH=$PATH:/data/data/com.topjohnwu.magisk/busybox
 elif [ $_busybox ]; then
   true
 else
@@ -106,13 +105,34 @@ printf "\rProgress : [${_done// /=}${_left// / }] ${_progress}%%"
 
 }
 
+# "cmd & spinner [message]"
+spinner() {
+  PID=$!
+  h=0; anim='-\|/'; 
+  while [ -d /proc/$PID ]; do
+	h=$(((h+1)%4))
+	printf "\r$@ [${anim:$h:1}]"
+  done
+}
+
 # Log files will be uploaded to termbin.com
 upload_logs() {
   $BBok && {
     echo -n "Testing internet connection "
     ping -q -c 1 -W 1 google.com >/dev/null 2>/dev/null && echo "- OK" || { echo "Error"; exit 1; }
-    [ -f $VERLOG ] && verUp=$(cat $VERLOG | nc termbin.com 9999) && echo "Verbose log URL: $verUp"
-    [ -f $LOG ] && logUp=$(cat $LOG | nc termbin.com 9999) && echo "Log URL: $logUp"
+	verUp=none; oldverUp=none; logUp=none; oldlogUp=none;
+	echo "Uploading logs"
+	[ -s $VERLOG ] && verUp=$(cat $VERLOG | nc termbin.com 9999)
+    [ -s $oldVERLOG ] && oldverUp=$(cat $oldVERLOG | nc termbin.com 9999)
+    [ -s $LOG ] && logUp=$(cat $LOG | nc termbin.com 9999)
+    [ -s $oldLOG ] && oldlogUp=$(cat $oldLOG | nc termbin.com 9999)
+	echo -n "Link: "
+	echo "$MODEL ($DEVICE) API $API\n$ROM\n$ID\n
+	O_Verbose: $oldverUp
+	Verbose:   $verUp
+	
+	O_Log: $oldlogUp
+	Log:   $logUp" | nc termbin.com 9999
   } || echo "Busybox not found!"
   exit
 }
@@ -141,6 +161,14 @@ fi
 # Import util_functions.sh
 [ -f /data/adb/magisk/util_functions.sh ] && . /data/adb/magisk/util_functions.sh || exit 1
 
+# Device Info
+# BRAND MODEL DEVICE API ABI ABI2 ABILONG ARCH
+BRAND=$(getprop ro.product.brand)
+MODEL=$(getprop ro.product.model)
+DEVICE=$(getprop ro.product.device)
+ROM=$(getprop ro.build.display.id)
+api_level_arch_detect
+
 # Version Number
 VER=$(grep_prop version $MODDIR/module.prop)
 # Version Code
@@ -167,24 +195,24 @@ N='\e[00;37;40m' # How to use (example): echo "${G}example${N}"
 }
 
 # Divider (based on $MODTITLE, $VER, and $REL characters)
-div="${Bl}$(printf '%*s' "$(($(echo $MODTITLE | wc -c)+$(echo $VER | wc -c)+$(echo $REL | wc -c)))" '' | tr " " '=')${N}"
+div="${Bl}$(printf '%*s' "$(echo $MODTITLE $VER $REL | tr " " '_' | wc -c)" '' | tr " " '=')${N}"
+
+# Heading
+head() {
+  clear
+  echo "$div"
+  echo "${W}$MODTITLE $VER${N}${Bl}($REL)${N}"
+  echo "by ${W}$AUTHOR${N}"
+  echo "$div"
+  echo "${W}$_bbname${N}"
+  echo "${Bl}$_bb${N}"
+  echo "$div"
+}
 
 #=========================== Main
 # > You can start your MOD here.
 # > You can add functions, variables & etc.
 # > Rather than editing the default vars above.
-
-
-# Terminal Debloater
-# by veez21
-clear
-echo "$div"
-echo "${W}$MODTITLE $VER${N}${Bl}($REL)${N}"
-echo "by ${W}$AUTHOR${N}"
-echo "$div"
-echo "${W}$_bbname${N}"
-echo "${Bl}$_bb${N}"
-echo "$div"
 
 use_aapt=false
 sysapp=0
@@ -386,34 +414,6 @@ enter_apk_name() {
   fi
 }
 
-revert_apps() {
-  list_systemized_apps
-  clear
-  echo "$div"
-  echo "Revert"
-  echo "$div"
-  echo ""
-  for i in $(seq 1 $((${#rev_app[@]}-1))); do
-    echo " ${Bl}$i${N} - ${W}${rev_app[$i]}${N}" | tr '_' ' '
-  done
-  echo ""
-  echo " 0 -  Exit"
-  echo -n "[CHOICE]: "
-  read revert
-  if [ "$revert" -gt ${#rev_app[@]} ] || [ "$revert" -lt 0 ] || [ "$revert" == "" ] || [ -n "$(echo $revert | tr -d '0-9')" ] ; then
-    echo "Invalid!"
-    exit 1
-  elif [ "$revert" == 0 ]; then
-    exit
-  else
-    echo "Reverting ${rev_app[$revert]}..." | tr '_' ' '
-    rm -rf ${rev_dir[$revert]}
-	rm -rf $MODDIR$SYSTEM2/etc/permissions/privapp-permissions-${rev_label[$revert]}.xml 2>$LOG >$LOG
-    echo "Done! Reboot to apply changes"
-    exit
-  fi
-}
-
 # Check apk size
 chk_apk_size() {
   dir_app=$(echo $1)
@@ -456,19 +456,7 @@ busybox mount -o rw,remount $MOUNTPATH 2>$LOG
 busybox mount -o remount,rw /cache 2>$LOG
 busybox mount -o rw,remount /cache 2>$LOG
 
-echo ""
-echo " 1 - Systemize Installed Apps (Listed)"
-echo " 2 - Systemize Installed Apps (Enter label) "
-echo " 3 - Systemize given APK"
-if [[ $(find $MODDIR -name "*.apk" 2>$LOG) ]]; then
-  echo " 4 - Revert Systemized Apps"
-fi
-echo " d - ${C}Donate${N}"
-echo " 0 - Exit"
-echo ""
-echo -n "[CHOICE]: "
- read choice
-if [ "$choice" == 1 ]; then
+menu_list_systemized_apps() {
   clear
   list_installed_apps 2>/dev/null
   clear
@@ -481,9 +469,11 @@ if [ "$choice" == 1 ]; then
   done
   echo ""
   echo " ${Bl}To systemize multiple apps, enter multiple number. Example:${N} \"1 $(echo ${#app[$((${#app[@]}/3))]}) $(echo ${#app[$((${#app[@]}/2))]})\""
+  echo " x - ${Bl}Back to Menu${N}"
   echo " 0 -  Exit"
   echo -n "[CHOICE]: "
   read installed
+  [ "$installed" == "x" ] && menu
   for i in $installed; do
     if [ "$i" -gt ${#app[@]} ] || [ "$i" -lt 0 ] || [ "$i" == "" ] || [ -n "$(echo $i | tr -d '0-9')" ] ; then
       echo "Invalid!"
@@ -530,27 +520,86 @@ if [ "$choice" == 1 ]; then
       fi
 	fi
   done
-  exit $?
-elif [ "$choice" == 2 ]; then
-  clear
-  enter_apk_name
-  exit $? 
-elif [ "$choice" == 3 ]; then
-  clear
-  enter_apk_dir
-  exit $?
-elif [ "$choice" == 4 ]; then
-  clear
-  revert_apps
-  exit $?
+  echo "Reboot to apply changes"
+  echo -n "Return to menu? < y | n >: "
+  read mchoice
+  [ "$mchoice" == "y" ] && menu || exit
+}
 
-elif [ "$choice" == "d" ] || [ "$choice" == "D" ]; then
-  am start https://paypal.me/veez21 >$LOG
-elif [ "$choice" == "logs" ]; then
-  upload_logs
-elif [ "$choice" == 0 ]; then
-  exit
-else  echo "Invalid!"
-  exit 1
-fi
-  
+revert_apps() {
+  list_systemized_apps
+  clear
+  echo "$div"
+  echo "Revert"
+  echo "$div"
+  echo ""
+  for i in $(seq 1 $((${#rev_app[@]}-1))); do
+    echo " ${Bl}$i${N} - ${W}${rev_app[$i]}${N}" | tr '_' ' '
+  done
+  echo ""
+  echo " ${Bl}To systemize multiple apps, enter multiple number. Example:${N} \"1 $(echo ${#rev_app[$((${#rev_app[@]}/3))]}) $(echo ${#rev_app[$((${#rev_app[@]}/2))]})\""
+  echo " x - ${Bl}Back to Menu${N}"
+  echo " 0 -  Exit"
+  echo -n "[CHOICE]: "
+  read revert
+  [ "$revert" == "x" ] && menu
+  for i in $revert; do
+    if [ "$i" -gt ${#rev_app[@]} ] || [ "$i" -lt 0 ] || [ "$i" == "" ] || [ -n "$(echo $i | tr -d '0-9')" ] ; then
+      echo "Invalid!"
+      exit 1
+    elif [ "$i" == 0 ]; then
+      exit
+    else
+      echo "Reverting ${rev_app[$i]}..." | tr '_' ' '
+      rm -rf ${rev_dir[$i]}
+	  rm -rf $MODDIR$SYSTEM2/etc/permissions/privapp-permissions-${rev_label[$i]}.xml 2>$LOG >$LOG
+    fi
+  done
+  echo "Reboot to apply changes"
+  echo -n "Return to menu? < y | n >: "
+  read mchoice
+  [ "$mchoice" == "y" ] && menu || exit
+}
+
+menu() {
+  head
+  echo ""
+  echo " 1 - Systemize Installed Apps (Listed)"
+  echo " 2 - Systemize Installed Apps (Enter label) "
+  echo " 3 - Systemize given APK"
+  if [[ $(find $MODDIR -name "*.apk" 2>$LOG) ]]; then
+    echo " 4 - Revert Systemized Apps"
+  fi
+  echo " d - ${C}Donate${N}"
+  echo " 0 - Exit"
+  echo ""
+  echo -n "[CHOICE]: "
+  read choice
+  if [ "$choice" == 1 ]; then
+    menu_list_systemized_apps
+  elif [ "$choice" == 2 ]; then
+    clear
+    enter_apk_name
+    exit $?
+  elif [ "$choice" == 3 ]; then
+    clear
+    enter_apk_dir
+    exit $?
+  elif [ "$choice" == 4 ]; then
+    clear
+    revert_apps
+    exit $?
+
+  elif [ "$choice" == "d" ] || [ "$choice" == "D" ]; then
+    am start https://paypal.me/veez21 >$LOG
+  elif [ "$choice" == "logs" ]; then
+    upload_logs
+  elif [ "$choice" == 0 ]; then
+    exit
+  else  echo "Invalid!"
+    exit 1
+  fi
+}
+
+menu
+exit $?
