Update stuff :3
Signed-off-by: Val Mandantes <mandantesv@gmail.com>

diff --git a/system/bin/systemize b/system/bin/systemize
--- a/system/bin/systemize
+++ b/system/bin/systemize
@@ -38,7 +38,6 @@ else
 fi
 
 #=========================== Set Busybox (Used by Magisk) up
-# > Do not touch!
 set_busybox() {
 	if [ -x "$1" ]; then
 		for i in $(${1} --list); do
@@ -74,7 +73,7 @@ else
 fi
 [ $? -ne 0 ] && exit $?
 alias echo='echo -e'
-[ -n "$LOGNAME" ] && alias clear='clear && echo'
+[ -n "$LOGNAME" ] && alias clear='echo'
 _bbname=$(busybox | head -n1)
 _bbname=${_bbname%'('*}
 BBok=true
@@ -134,7 +133,7 @@ W='\e[01;37m'		# WHITE TEXT
 BGBL='\e[1;30;47m'	# Background W Text Bl
 N='\e[0m'			# How to use (example): echo "${G}example${N}"
 loadBar=' '			# Load UI
-# Remove colors if -nc or in ADB Shell
+# Remove color codes if -nc or in ADB Shell
 [ -n "$1" -a "$1" == "-nc" ] && shift && NC=true
 [ "$NC" -o -n "$LOGNAME" ] && {
 	G=''; R=''; Y=''; B=''; V=''; Bl=''; C=''; W=''; N=''; BGBL=''; loadBar='=';
@@ -144,7 +143,7 @@ loadBar=' '			# Load UI
 character_no=$(echo $MODTITLE $VER $REL | tr " " '_' | wc -c)
 div="${Bl}$(printf '%*s' "${character_no}" '' | tr " " "=")${N}"
 
-# Title Div :3
+# Title Div
 title_div() {
 	no=$(echo $@ | wc -c)
 	extdiv=$((no-character_no))
@@ -183,11 +182,17 @@ spinner() {
 	done
 }
 
+# test_connection
+test_connection() {
+	echo -n "Testing internet connection "
+	ping -q -c 1 -W 1 google.com >/dev/null 2>/dev/null && echo "- OK" || { echo "Error"; false; }
+}
+
 # Log files will be uploaded to termbin.com
 upload_logs() {
 	$BBok && {
-		echo -n "Testing internet connection "
-		ping -q -c 1 -W 1 google.com >/dev/null 2>/dev/null && echo "- OK" || { echo "Error"; exit 1; }
+		test_connection
+		[ $? -ne 0 ] && exit
 		verUp=none; oldverUp=none; logUp=none; oldlogUp=none;
 		echo "Uploading logs"
 		[ -s $VERLOG ] && verUp=$(cat $VERLOG | nc termbin.com 9999)
