Better detection for use_cmd
Signed-off-by: Val Mandantes <mandantesv@gmail.com>

diff --git a/system/bin/systemize b/system/bin/systemize
--- a/system/bin/systemize
+++ b/system/bin/systemize
@@ -70,9 +70,11 @@ RESCAN=true
 se_set=false
 
 # Method
-[ "$(grep_prop selinux $MODDIR/module.prop)" == "true" ] && { use_cmd=true; se_set=true; } || use_cmd=false
-[ $(getenforce) == "Permissive" ] && use_cmd=true || use_cmd=false
-[ $LOGNAME ] && use_cmd=true || use_cmd=false
+[ "$(grep_prop selinux $MODDIR/module.prop)" == "true" ] && { use_cmd=true; se_set=true; } || {
+	use_cmd=false
+	[ $(getenforce) == "Permissive" ] && use_cmd=true || use_cmd=false
+	[ $LOGNAME ] && use_cmd=true || use_cmd=false
+}
 method="ls /data/data"
 detect="codePath=$SYSTEM|targetSdk=0|codePath=/vendor/overlay"
 if $use_cmd; then
@@ -449,17 +451,22 @@ set_selinux() {
 	echo " 0 - Exit"
 	echo -n "[CHOICE]: "
 	read sechoice
-	if $se_set; then
-		set_file_prop selinux false $MODDIR/module.prop
-		echo "Set to false"
-		echo "Exiting script to apply changes"
-		exit
-	else
-		set_file_prop selinux true $MODDIR/module.prop
-		echo "Set to true"
-		echo "Exiting script to apply changes"
-		exit
-	fi
+	case "$sechoice" in
+		x|X) menu;;
+		c|C) if $se_set; then
+				set_file_prop selinux false $MODDIR/module.prop
+				echo "Set to false"
+				echo "Exiting script to apply changes"
+				exit
+			else
+				set_file_prop selinux true $MODDIR/module.prop
+				echo "Set to true"
+				echo "Exiting script to apply changes"
+				exit
+			fi;;
+		0) exit;;
+		*) echo "Invalid!"; exit;;
+	esac
 }
 
 menu() {
